workflows:
 react-native:
  name: React Native Apptest
  environment: 
    vars:
      XCODE_WORKSPACE: "{{ADD WORKSPACE NAME HERE}}"
      XCODE_SCHEME: "{{ADD SCHEME NAME HERE}}"
    node: latest
  triggering:
    events:
      - push
    branch_patterns:
      - pattern: master
        include: true
        source: true
  scripts:
    - yarn install
    - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
    - |
      # build Android
      cd android
      ./gradlew clean && ./gradlew assembleRelease
  artifacts:
    - android/app/build/outputs/**/*.apk
  publishing:
        email:
          recipients:
            - arunkumarkv08@gmail.com


